sudo: required
services:
  - docker

before_install:
  - docker build -t grantgolden/docker-react -f Dockerfile.dev .

script:
  - docker run grantgolden/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'docker'
  env: 'Docker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-282732728696'
  bucket_path: 'docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: '$AWS_SECRET_KEY'
